### ISSUE TITLE
TypeError related to custom protocol name

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#31]
Hi, 

One of my protocol's name is '24', it causes the following error : `TypeError: type.__new__() argument 1 must be str, not int`.
I guess it should be easily fixable by tweaking yaml loading parameters or adding a `str` conversion somewhere but I don't understand why the name can't be an int in the first place.

Full log below

Merry Christmas :)

```py
Traceback (most recent call last):
  File "/people/lerner/anaconda3/envs/pyannote/bin/pyannote-speaker-embedding", line 11, in <module>
    load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-speaker-embedding')()
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/people/lerner/pyannote/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 180, in <module>
    from .base import Application
  File "/people/lerner/pyannote/pyannote-audio/pyannote/audio/applications/base.py", line 40, in <module>
    from pyannote.database import FileFinder
  File "/people/lerner/pyannote/pyannote-database/pyannote/database/__init__.py", line 62, in <module>
    DATABASES, TASKS = add_custom_protocols()
  File "/people/lerner/pyannote/pyannote-database/pyannote/database/custom.py", line 314, in add_custom_protocols
    {'__init__': get_init(register)})
TypeError: type.__new__() argument 1 must be str, not int
```

**Comment by hbredin** [comment]
Database names are used as class names. That is why they can only be instances of `str`.

Commit 709f758 (forcing conversion to str) fixes the issue and will be part of next `pyannote.database` release.

**Comment by hbredin** [comment]
This is now part of  `pyannote.database` 2.4.2
