### ISSUE TITLE
Error in dataloader : 'PosixPath' object has no attribute 'format'

### ISSUE THREAD

**Issue by marianne-m** [pyannote/pyannote-database#77]
Hi !
I have an error in the data loader : 
```
Traceback (most recent call last):
  File "main.py", line 292, in <module>
    args.func(args)
  File "main.py", line 134, in run
    trainer.fit(model)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1439, in _call_setup_hook
    self.call_hook("setup", stage=fn)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
    output = model_fx(*args, **kwargs)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/audio/core/model.py", line 349, in setup
    self.task.setup()
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 51, in setup
    for f in self.protocol.train():
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 363, in subset_helper
    yield self.preprocess(file)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 329, in preprocess
    return ProtocolFile(current_file, lazy=self.preprocessors)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 87, in __init__
    self._store[key] = precomputed[key]
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 122, in __getitem__
    value = self.lazy[key](self)
  File "/linkhome/rech/genini01/uzm31mf/.conda/envs/vtc2/lib/python3.8/site-packages/pyannote/database/loader.py", line 128, in __call__
    loaded = load_rttm(self.path.format(**sub_file))
AttributeError: 'PosixPath' object has no attribute 'format'
```

My version of pyannote-database is : 
```pyannote.database       4.1.1```

This error seems to happen while trying to load files that don't have annotations in the `rttm` file.

**Comment by hbredin** [comment]
Thanks. Would you mind providing me with a minimal reproducible example?

**Comment by marianne-m** [comment]
Sure !

The `database.yml` file : 
```
Databases:
  BBT: /home/vtc_2/BBT/{uri}.wav
Protocols:
  BBT:
    SpeakerDiarization:
      data:
        train:
          annotated: /home/vtc_2/BBT/train/data.train.uem
          annotation: /home/vtc_2/BBT/train/data.train.rttm
          uri: /home/vtc_2/BBT/train/data.train.lst
```

The `data.train.lst` file : 
```
train/file_1
train/file_2
```

The `data.train.uem` file : 
```
train/file_1 1 0.000 60.00
train/file_2 1 0.000 60.00
```

The `data.train.rttm` file : 
```
SPEAKER train/file_1 1 8.3423 1.4036 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 10.5575 1.1089 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 16.7604 1.5248 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 22.0109 0.7103 <NA> <NA> MA2 <NA> <NA>
SPEAKER train/file_1 1 23.5186 1.4024 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 26.6089 1.7857 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 37.4706 0.9533 <NA> <NA> MOT* <NA> <NA>
SPEAKER train/file_1 1 38.8375 1.1234 <NA> <NA> MOT* <NA> <NA>
SPEAKER train/file_1 1 40.9585 0.7524 <NA> <NA> MOT* <NA> <NA>
SPEAKER train/file_1 1 46.7806 0.6350 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 52.3473 1.1804 <NA> <NA> MA1 <NA> <NA>
SPEAKER train/file_1 1 58.4449 1.5083 <NA> <NA> MOT* <NA> <NA>
```

When I load the database : 
```
from pyannote.database import get_protocol
protocol = get_protocol('BBT.SpeakerDiarization.data')
for resource in protocol.train():
    print(resource["uri"])
```
I get the error : 
```
train/file_1
Traceback (most recent call last):
  File "load_db.py", line 3, in <module>
    for resource in protocol.train():
  File "/home/marianne/anaconda3/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 363, in subset_helper
    yield self.preprocess(file)
  File "/home/marianne/anaconda3/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 329, in preprocess
    return ProtocolFile(current_file, lazy=self.preprocessors)
  File "/home/marianne/anaconda3/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 87, in __init__
    self._store[key] = precomputed[key]
  File "/home/marianne/anaconda3/lib/python3.8/site-packages/pyannote/database/protocol/protocol.py", line 122, in __getitem__
    value = self.lazy[key](self)
  File "/home/marianne/anaconda3/lib/python3.8/site-packages/pyannote/database/loader.py", line 128, in __call__
    loaded = load_rttm(self.path.format(**sub_file))
AttributeError: 'PosixPath' object has no attribute 'format'
```

**Comment by hbredin** [comment]
Thanks. Could you try https://github.com/pyannote/pyannote-database/pull/78 and let me know if that fixes your issue?

**Comment by marianne-m** [comment]
Yes it works ! Thanks

**Comment by hbredin** [comment]
Part of (just released) pyannote.database 4.1.3
